#MOSTRAR LOS ALUMNOS QUE TENGAN MENOS DE UN 5 de NOTA EN TODAS LAS ASIGNATURAS (CATALAN E HISTORIA)
#Y ORDENARLAS POR MATERIA.

SELECT nombre, nota, nombreAsig from ALUMNO,ES_EVALUADO,ASIGNATURA
where ALUMNO.DNIAlumno = ES_EVALUADO.DNIAlumno AND ES_EVALUADO.nota <5 ORDER BY ASIGNATURA.nombreAsig;

