CONSULTAS
#SUBIR UN PUNTO LA NOTA DE LOS ALUMNOS SUSPENDIDOS
UPDATE ES_EVALUADO SET (nota=nota+1) WHERE (nota<5);


SUBCONSULTAS
#MOSTRAR LOS ALUMNOS QUE TENGAN UNA NOTA MENOR A LA MEDIA 5 o menos de 5.

Select (SELECT nombre FROM ALUMNO WHERE DNIAlumno = ES_EVALUADO.DNIAlumno) AS Nombre ,DNIALUMNO, nota from ES_EVALUADO
where ES_EVALUADO.nota <(select avg(ES_EVALUADO.nota) from ES_EVALUADO);

#QUITAR UN 20% DE LA NOTA DE CATALÁN POR NO CALLAR EN CLASES Y ESCUCHAR MÚSICA MUY ALTA
UPDATE ES_EVALUADO SET nota=nota-(nota*2/10) WHERE idAsignatura IN (SELECT idAsignatura FROM ASIGNATURA WHERE nombreAsig = 'Catalán');
